Dimension des capteur US #476
Sam-Existence/ErabliereApi pull request #17
Opened 2024-05-28 15:35 UTC by ZacharyGagnon

2024-05-28 18:44 UTC, IsatisSnowfox requested changes
Certaines questions, recommandations et trucs à changer

2024-05-28 18:44 UTC, IsatisSnowfox commented on ErabliereApi/Controllers/CapteurController.cs
> +
Plutôt que de mettre == false, tu peux plutôt mettre ! devant ta condition.

2024-05-28 18:44 UTC, IsatisSnowfox commented on ErabliereIU/src/donnees/sub-panel/capteur-pannels.component.ts
> +        <div [ngClass]="Dimension" *ngFor="let capteur of capteurs">
Utilise plutôt [@for](https://v17.angular.io/api/core/for)

2024-05-28 18:44 UTC, IsatisSnowfox commented on ErabliereModel/Capteur.cs
Pour éviter de faire un appel backend par capteur pour le redimensionnement, il serait préférable de mettre le nombre de colonnes sur l'érablière

2024-05-28 18:44 UTC, IsatisSnowfox commented on ErabliereIU/src/styles.css
> +body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif; }
Évite de mettre ton CSS inline comme ça, ça le rend vite illisible

2024-05-28 18:44 UTC, IsatisSnowfox commented on ErabliereIU/src/styles.css
Pourquoi as-tu changé le style global du site ?

2024-05-28 18:44 UTC, IsatisSnowfox commented on ErabliereIU/src/donnees/sub-panel/capteur-pannels.component.ts
> +    }
Il aurait été préférable de juste garder le nombre de colonnes dans une variable et directement changer la classe dans le template (par exemple en faisant `'border-top col-md-' + taille` ou `'border-top col-md-' + 12 / nbColonnes`)

2024-05-28 18:44 UTC, IsatisSnowfox commented on ErabliereIU/src/donnees/sub-panel/capteur-pannels.component.ts
>        </div>
Sépare ton template de ton TypeScript

2024-05-28 18:44 UTC, IsatisSnowfox commented on ErabliereIU/src/donnees/sub-panel/capteur-pannels.component.ts
> +  }
Ta méthode récupères les capteurs, pas juste les dimensions. Elle est mal nommée.
Aussi, comme tu as déjà accès aux dimensions dans ta liste de capteurs, pourquoi tu les enregistres à nouveau ?
Enfin, la méthode va juste enregistrer la dimension du dernier capteur (elle écrase Dimension à chaque fois)

2024-05-28 18:44 UTC, IsatisSnowfox commented on ErabliereIU/src/donnees/sub-panel/capteur-pannels.component.ts
> +  public Dimension: string | undefined = "border-top col-md-6";
En JavaScript, les variables s'écrivent en camelCase, ta variable devrait donc se nommer `dimension`
Aussi, tu pourrais faire `dimension?: string` c'est l'équivalent de `Dimension: string | undefined`

2024-05-28 21:06 UTC, ZacharyGagnon commented on ErabliereModel/Capteur.cs
Non, vu que si on veut améliorer la fonctionnalité pour changer un capteur à la fois, ce serait mieux de le laisser comme ça.

2024-05-28 21:14 UTC, ZacharyGagnon commented on ErabliereIU/src/donnees/sub-panel/capteur-pannels.component.ts
> +    }
oui mais frederick a dit "Dans la table Capteur, une colonne de type numérique ou string pourrait être utilisé pour sauvegarder la dimenssion du grahique. Les valeurs serait soit 1, 2, ..., 12 ou md-3, lx-12, etc." dans sont document d'explication

2024-05-28 21:49 UTC, ZacharyGagnon commented on ErabliereIU/src/donnees/sub-panel/capteur-pannels.component.ts
> +  }
Aussi, comme tu as déjà accès aux dimensions dans ta liste de capteurs, pourquoi tu les enregistres à nouveau ? -> ces parce que je n'ai pas acces a la liste de cpateur dans la methode je sais pas pourquoi. le reste je l'ai changer.

2024-05-29 00:28 UTC, Sam-Existence commented on ErabliereIU/src/styles.css
En théorie (j'imagine qu'en vrai ça dépend du navigateur) html,body { height: 100% } est déjà le style par défaut, même chose pour body { margin: 0 }. Dans le cas du font-family, à moins que Frédérique ne t'ait dit de changer la police, ce n'est pas notre décision.

2024-05-29 00:36 UTC, IsatisSnowfox commented on ErabliereIU/src/styles.css
@Sam-Existence Le problème de le remettre, c'est que si ça a été écrasé plus bas, ça peut poser problème (même si vu ou c'est mis il y a peu de chances que quoique ce soit ait un poids de sélecteur moins élevé)

2024-05-29 06:56 UTC, Sam-Existence commented
Ce n'est toujours pas parfait, mais j'ai fait quelques changements

2024-05-31 01:49 UTC, Sam-Existence approved these changes

2024-05-31 02:24 UTC, IsatisSnowfox approved these changes

2024-05-31 02:24 UTC, merged